service: statPage

frameworkVersion: ">=1.7.0 <2.0.0"

custom:
  bucket: stats-page-details

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  toggleStat:
    handler: handler.toggleStat
    environment:
      BUCKET: ${self:custom.bucket}
  updateStat:
    handler: handler.updateStat
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          path: updateStat
          method: put
          cors: true
  currStat:
    handler: handler.currStat
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          method: get
          path: currStat