service: statPage

frameworkVersion: ">=1.7.0 <2.0.0"

custom:
  bucket: stats-page-details
  statusTopic:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - sns
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - statusTopic

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - "sns:Publish"
      Resource:
        - ${self:custom.statusTopic}

functions:
  toggleStat:
    handler: handler.toggleStat
    environment:
      BUCKET: ${self:custom.bucket}
      TOPIC: ${self:custom.statusTopic}
  updateStat:
    handler: handler.updateStat
    environment:
      BUCKET: ${self:custom.bucket}
      TOPIC: ${self:custom.statusTopic}
    events:
      - http:
          path: updateStat
          method: post
          cors: true
  currStat:
    handler: handler.currStat
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          method: get
          path: currStat